local:
  chrome:
    driverPath: /chromedriver_win32/chromedriver72.0.3626.69.exe
    dataPath: C:/Users/hcwang.docker/AppData/Local/Google/Chrome/User Data

  fsPath:
    tmp: D:/fsPath/tmp
    img: D:/fsPath/img
    originZip: D:/fsPath/originZip

  host:
    inner: http://127.0.0.1
    outer: http://39.107.236.187
    portainer:
      inner: http://192.168.0.106:9000/#/containers
      outer: http://39.107.236.187:9000/#/containers
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.202.16.9:3306/information?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root


