## dev环境使用是配置
server:
  port: 8083
  servlet:
    context-path: /download


spring:
  profiles:
    active: devMac
    servlet:
      multipart:
        max-file-size: 900000000
        max-request-size: 900000000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    content-type: text/html
    mode: HTML5
    cache: false
  ## freemarker
  #spring.freemarker.allow-request-override=false
  #spring.freemarker.cache=true
  #spring.freemarker.check-template-location=true
  #spring.freemarker.charset=UTF-8
  #spring.freemarker.content-type=text/html
  #spring.freemarker.expose-request-attributes=false
  #spring.freemarker.expose-session-attributes=false
  #spring.freemarker.expose-spring-macro-helpers=false
  freemarker:
    charset: UTF-8
    content-type: text/html
    cache: false
    suffix: .html


#  可以在application 上面加注解
#  效果相同
#  @MapperScan(value = "demo.spring.boot.demospringboot.mybatis.mapper")
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml,classpath*:demomaster/mapper/*Mapper.xml
  config-location: classpath:mybatis/config/mybatis-config.xml

  ##静态资源
resources:
  ##静态资源
  ## -- 如果不配置，都可以访问
  ## -- 如果配置，都可以只能访问指定路径下的
  ## http://localhost:8081/chao/static.txt
  ## http://localhost:8081/chao/public.txt
  static-locations: classpath:/static/,classpath:/public/