local:
  chrome:
    driverPath: /driver/chromedriver_mac64/chromedriver
    dataPath: /Users/chao/Library/Application Support/Google/Chrome

  fsPath:
    tmp: /Users/chao/data/tmp
    img: /Users/chao/data/img
    originZip: /Users/chao/data/originZip


