local:
  chrome:
    driverPath: /chromedriver_win32/chromedriver72.0.3626.69.exe
    dataPath: C:/Users/hcwang.docker/AppData/Local/Google/Chrome/User Data

  fsPath:
    tmp: D:/fsPath/tmp
    img: D:/fsPath/img
    originZip: D:/fsPath/originZip

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.202.16.9:3306/information?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: root


