local:
  chrome:
    driverPath: /driver/chromedriver_mac64/chromedriver
    dataPath: /Users/chao/Library/Application Support/Google/Chrome

  fsPath:
    tmp: /Users/chao/data/tmp
    img: /Users/chao/data/img
    originZip: /Users/chao/data/originZip
    proZip: /Users/chao/data/proZip

  host:
    inner: http://127.0.0.1
    outer: http://39.107.236.187
    portainer:
      inner: http://127.0.0.1:9000/#/containers
      outer: http://39.107.236.187:9000/#/containers
    docker:
      api: http://127.0.0.1:3375
      master: host.docker.internal
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ASPDocker?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    #    url: jdbc:mysql://192.168.0.106:7001/ASPDocker?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456

