local:
  chrome:
    driverPath: /driver/chromedriver_mac64/chromedriver
    dataPath: /Users/chao/Library/Application Support/Google/Chrome

  fsPath:
    tmp: /Users/chao/data/tmp
    img: /Users/chao/data/img
    originZip: /Users/chao/data/originZip

  host:
    inner: http://127.0.0.2
    outer: http://39.107.236.187

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ASPDocker?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456

