local:
  chrome:
    driverPath: /driver/chromedriver_mac64/chromedriver
    dataPath: /Users/chao/Library/Application Support/Google/Chrome

  fsPath:
    tmp: /data/fsPath/tmp
    img: /data/fsPath/img
    originZip: /data/fsPath/originZip

  host:
    inner: http://192.168.0.106
    outer: http://39.107.236.187
    portainer:
      inner: http://192.168.0.106:9000/#/containers
      outer: http://39.107.236.187:9000/#/containers
    docker:
      api: http://192.168.0.106:5555

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ASPDocker?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: 123456