CREATE TABLE `PROJECT` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `criteriaId` longtext COLLATE utf8_bin COMMENT 'ASP唯一id',
  `project_name` text COLLATE utf8_bin COMMENT '项目名称',
  `project_update_time` text COLLATE utf8_bin COMMENT '项目更新时间',
  `project_type` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '类型(VIP/COMMON)',
  `project_zip_status` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '项目的下载包类型(流/盘)',
  `project_pan_address` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目的网盘地址',
  `file_real_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '真实文件名称',
  `docker_zip_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker压缩包的真实名称',
  `html_body` longtext COLLATE utf8_bin COMMENT '网页Body',
  `source_url` text COLLATE utf8_bin COMMENT 'ASPURL',
  `language` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目语言',
  `size2` text COLLATE utf8_bin COMMENT '项目大小',
  `size_num` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目大小数字',
  `size_type` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目大小type(k,M,G)',
  `official_website` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '官网地址',
  `show_website` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '展示网址',
  `download_sum` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目下载次数',
  `introduction` longtext COLLATE utf8_bin COMMENT '项目介绍(文字)',
  `content_imgs` text COLLATE utf8_bin COMMENT '项目介绍(图片)',
  `runtime` text COLLATE utf8_bin COMMENT '运行环境',
  `download_urls` text COLLATE utf8_bin COMMENT '项目下载URL',
  `docker_port` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker的端口号',
  `docker_image_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker的镜像名称',
  `docker_container_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker的容器名称',
  `docker_shell_create` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker的创建命令',
  `docker_shell_run` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker的启动命令',
  `docker_shell_stop` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker的停止命令',
  `docker_shell_container_remove` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker容器移除命令',
  `docker_shell_image_remove` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker镜像移除命令',
  `docker_status` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker状态,创建.运行中,停止,容器移除,镜像移除',
  `project_status` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'project状态,没有状态,可以使用,暂不可使用,完全不能使用',
  `http_inner_address` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '内网的访问地址',
  `http_out_address` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '外网的访问地址',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `index111` (`criteriaId`(1000)) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;