CREATE TABLE `project_plus` (
  `id` int(255) NOT NULL AUTO_INCREMENT,
  `criteriaId` longtext COLLATE utf8_bin COMMENT '唯一id',
  `project_name` text COLLATE utf8_bin COMMENT '项目-名称',
  `project_update_time` text COLLATE utf8_bin COMMENT '项目-更新时间',
  `project_type` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-类型(VIP/COMMON)',
  `project_price` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-价格',
  `project_package_type` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-下载包类型(流/text)',
  `project_pan_address` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-网盘地址',
  `project_real_file_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-真实文件名称',
  `project_html_body` longtext COLLATE utf8_bin COMMENT '项目-网页Body',
  `project_source_url` text COLLATE utf8_bin COMMENT '项目-源ASPURL',
  `project_language` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-开发语言',
  `project_size2` text COLLATE utf8_bin COMMENT '项目-大小',
  `project_size_num` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-大小数字',
  `project_size_type` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-大小type(k,M,G)',
  `project_imgs` text COLLATE utf8_bin COMMENT '项目-介绍(图片)',
  `project_imgs_default` text COLLATE utf8_bin COMMENT '项目-默认的图片',
  `project_runtime` text COLLATE utf8_bin COMMENT '项目-运行环境',
  `project_official_website` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-官网地址',
  `project_show_website` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-展示网址',
  `project_download_urls` text COLLATE utf8_bin COMMENT '项目-下载URL',
  `project_download_sum` varchar(255) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-下载次数',
  `project_introduction` longtext COLLATE utf8_bin COMMENT '项目-介绍(文字)',
  `project_status` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-状态,可用/废弃/暂定',
  `project_mark` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-备注',
  `project_can_running` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '项目-是否正常运行',
  `docker_image_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker-镜像-名称',
  `docker_image_shell_remove` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker-镜像-移除命令',
  `docker_status` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker-状态,创建.运行中,停止,容器移除,镜像移除',
  `docker_container_id` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker-容器-完整id',
  `docker_container_name` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker-容器-名称',
  `docker_container_port` varchar(10) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker-端口号',
  `docker_container_shell_create` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker-容器-创建命令',
  `docker_container_shell_run` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker-容器-启动命令',
  `docker_container_shell_stop` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker-容器-停止命令',
  `docker_container_shell_remove` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT 'docker-容器-移除命令',
  `address_container_outer` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '地址-容器外网',
  `address_container_inner` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '地址-容器内网',
  `address_project_front` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '地址-项目前端',
  `address_project_background` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '地址-项目后台',
  `address_project_background_account_passwd` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '地址-项目后台-账号密码',
  `update_time` varchar(100) COLLATE utf8_bin DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `index111` (`criteriaId`(100)) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11322 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;